services:
  rfactor-server:
    image: rf2-linux-server-nurb-dtm-alfa
    container_name: rf2-linux-server-test
    volumes:
      - /mnt/containers/rf2-server-test/UserData:/server/UserData:rw
      - /mnt/containers/rf2-server-test/var-log:/mnt/host-monitored:rw
    ports:
      - 45100:5900
      - 8001:8000
      - 64297:64297/tcp
      - 64298:64298/udp
      - 64299:64299/udp
      - 54297:54297/tcp
      - 54297:54297/udp
    environment:
      - VNC_PASSWORD=password
      - HTTP_SERVER_PORT=65297
      - SIMULATION_PORT=55297
    command: /bin/bash -c "/scripts/startup.sh"
    restart: unless-stopped
