services:
   rfactor-server:
    image: rf2-linux-server-barhain-endu
    container_name: rf2-linux-server-barhain-dev
    volumes:
      - /mnt/containers/rf2server-bahrain/UserData:/server/UserData
    ports:
      - 46100:5900
      - 65297:65297/tcp
      - 65298:65298/udp
      - 65299:65299/udp
      - 55297:55297/tcp
      - 55297:55297/udp
    environment:
      - VNC_PASSWORD=password
      - HTTP_SERVER_PORT=65297
      - SIMULATION_PORT=55297
    command: /bin/bash -c "/scripts/startup.sh"
    restart: unless-stopped
