services:
  rfactor-server:
    image: empty-rf2-server
    container_name: rf2-linux-server-test
    ports:
      - 5900:5900
    environment:
      - RUNTIME_USER_HOME=/root
      - VNC_PASSWORD=password
    command: /bin/bash -c "/scripts/startup.sh"
    # command: /bin/bash -c "tail -f /dev/null"
